---
  - name: Upload tar.gz Kibana from remote URL
    get_url:
      url: "https://sourceforge.net/projects/kibana.mirror/files/v7.17.5/Kibana%20{{ kibana_version }}.tar.gz/download"
      dest: "/tmp/Kibana%20{{ kibana_version }}.tar.gz"
      mode: 0755
      timeout: 60
      force: true
      validate_certs: false
    register: get_kibana
    until: get_kibana is succeeded
    tags: kibana
  - name: Create directrory for Kibana ({{ kibana_home }})
    file:
      path: "{{ kibana_home }}"
      state: directory
      mode: 0644
    tags: kibana
  - name: Extract Kibana in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/Kibana%20{{ kibana_version }}.tar.gz"
      dest: "{{ kibana_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ kibana_home }}/bin/kibana"
    tags:
      - kibana
  - name: Set environment Kibana
    become: true
    template:
      src: templates/kib.sh.j2
      dest: /etc/profile.d/kib.sh
      mode: 0644
    tags: kibana
